-- INSERT DATA
INSERT INTO discipline (disciplineid, codecomp, namecomp, codedom, namedom) VALUES (37, 'SP', 'Institut d''Etudes Politiques', 'DSP', 'Droit et Sciences politiques');
INSERT INTO discipline (disciplineid, codecomp, namecomp, codedom, namedom) VALUES (6, 'DA', 'Faculté de Droit', 'DSP', 'Droit et Sciences politiques');
INSERT INTO discipline (disciplineid, codecomp, namecomp, codedom, namedom) VALUES (26, 'PI', 'Centre d''Etudes Internationales de la Propriété Intellectuel', 'DSP', 'Droit et Sciences politiques');
INSERT INTO discipline (disciplineid, codecomp, namecomp, codedom, namedom) VALUES (17, 'GO', 'Faculté de Geographie et d''Aménagement', 'EDD', 'Environnement et Développement Durable');
INSERT INTO discipline (disciplineid, codecomp, namecomp, codedom, namedom) VALUES (34, 'SC', 'IUT de Schiltigheim', 'SIT', 'Sciences de l''Ingénieur et Technologie');
INSERT INTO discipline (disciplineid, codecomp, namecomp, codedom, namedom) VALUES (40, 'TS', 'IUT d Illkirch', 'SIT', 'Sciences de l''Ingénieur et Technologie');
INSERT INTO discipline (disciplineid, codecomp, namecomp, codedom, namedom) VALUES (15, 'HA', 'IUT de Haguenau', 'SIT', 'Sciences de l''Ingénieur et Technologie');
INSERT INTO discipline (disciplineid, codecomp, namecomp, codedom, namedom) VALUES (14, 'FM', 'Institut Universitaire de Formation des Maitres', 'O', 'Autres');
INSERT INTO discipline (disciplineid, codecomp, namecomp, codedom, namedom) VALUES (33, 'RI', 'Institut Traducteurs,Interprètes & Relations Internationales', 'SHSLA', 'Sciences humaines et sociales, Langues et Art');
INSERT INTO discipline (disciplineid, codecomp, namecomp, codedom, namedom) VALUES (35, 'SH', 'UFR des Sciences Historiques', 'SHSLA', 'Sciences humaines et sociales, Langues et Art');
INSERT INTO discipline (disciplineid, codecomp, namecomp, codedom, namedom) VALUES (36, 'SO', 'UFR Sciences Sociales, Pratiques Sociales & Développement', 'SHSLA', 'Sciences humaines et sociales, Langues et Art');
INSERT INTO discipline (disciplineid, codecomp, namecomp, codedom, namedom) VALUES (38, 'TC', 'Institut de Théologie Catholique', 'SHSLA', 'Sciences humaines et sociales, Langues et Art');
INSERT INTO discipline (disciplineid, codecomp, namecomp, codedom, namedom) VALUES (39, 'TP', 'Institut de Théologie Protestante', 'SHSLA', 'Sciences humaines et sociales, Langues et Art');
INSERT INTO discipline (disciplineid, codecomp, namecomp, codedom, namedom) VALUES (3, 'AR', 'UFR des Arts', 'SHSLA', 'Sciences humaines et sociales, Langues et Art');
INSERT INTO discipline (disciplineid, codecomp, namecomp, codedom, namedom) VALUES (8, 'ED', 'UFR Sciences de l''Education', 'SHSLA', 'Sciences humaines et sociales, Langues et Art');
INSERT INTO discipline (disciplineid, codecomp, namecomp, codedom, namedom) VALUES (9, 'EF', 'Institut International d''Etudes Françaises', 'SHSLA', 'Sciences humaines et sociales, Langues et Art');
INSERT INTO discipline (disciplineid, codecomp, namecomp, codedom, namedom) VALUES (18, 'JR', 'Centre Universitaire d''Enseignement du Journalisme', 'SHSLA', 'Sciences humaines et sociales, Langues et Art');
INSERT INTO discipline (disciplineid, codecomp, namecomp, codedom, namedom) VALUES (19, 'LA', 'UFR des Langues & Sciences Humaines Appliquées', 'SHSLA', 'Sciences humaines et sociales, Langues et Art');
INSERT INTO discipline (disciplineid, codecomp, namecomp, codedom, namedom) VALUES (20, 'LT', 'UFR des Lettres', 'SHSLA', 'Sciences humaines et sociales, Langues et Art');
INSERT INTO discipline (disciplineid, codecomp, namecomp, codedom, namedom) VALUES (21, 'LV', 'UFR des Langues Vivantes', 'SHSLA', 'Sciences humaines et sociales, Langues et Art');
INSERT INTO discipline (disciplineid, codecomp, namecomp, codedom, namedom) VALUES (24, 'MU', 'Centre de Formation de Musiciens Intervenants', 'SHSLA', 'Sciences humaines et sociales, Langues et Art');
INSERT INTO discipline (disciplineid, codecomp, namecomp, codedom, namedom) VALUES (27, 'PL', 'UFR Philosophie, Linguistique, Sciences de l''Education', 'SHSLA', 'Sciences humaines et sociales, Langues et Art');
INSERT INTO discipline (disciplineid, codecomp, namecomp, codedom, namedom) VALUES (28, 'PS', 'Faculté de Psychologie', 'SHSLA', 'Sciences humaines et sociales, Langues et Art');
INSERT INTO discipline (disciplineid, codecomp, namecomp, codedom, namedom) VALUES (32, 'OD', 'Faculté de Chirurgie Dentaire', 'SS', 'Santé et Sport');
INSERT INTO discipline (disciplineid, codecomp, namecomp, codedom, namedom) VALUES (42, '00', 'Autres', 'O', 'Autres');
INSERT INTO discipline (disciplineid, codecomp, namecomp, codedom, namedom) VALUES (2, 'AP', 'UFR Sc. & Techniques des Activites Physiques & Sportives', 'SS', 'Santé et Sport');
INSERT INTO discipline (disciplineid, codecomp, namecomp, codedom, namedom) VALUES (22, 'MD', 'Faculté de Médecine ', 'SS', 'Santé et Sport');
INSERT INTO discipline (disciplineid, codecomp, namecomp, codedom, namedom) VALUES (43, '01', 'Jardin des Sciences', 'O', 'Autres');
INSERT INTO discipline (disciplineid, codecomp, namecomp, codedom, namedom) VALUES (44, '02', 'Logcri', 'O', 'Autres');
INSERT INTO discipline (disciplineid, codecomp, namecomp, codedom, namedom) VALUES (25, 'PH', 'Faculté de Pharmacie', 'SS', 'Santé et Sport');
INSERT INTO discipline (disciplineid, codecomp, namecomp, codedom, namedom) VALUES (1, 'AG', 'Institut de Préparation à l''Administration Génerale', 'EG', 'Economie et Gestion');
INSERT INTO discipline (disciplineid, codecomp, namecomp, codedom, namedom) VALUES (10, 'EG', 'Faculté de Sciences Economiques & de Gestion', 'EG', 'Economie et Gestion');
INSERT INTO discipline (disciplineid, codecomp, namecomp, codedom, namedom) VALUES (11, 'EM', 'Ecole de Management de Strasbourg', 'EG', 'Economie et Gestion');
INSERT INTO discipline (disciplineid, codecomp, namecomp, codedom, namedom) VALUES (13, 'ET', 'Département des Etudes Territoriales', 'EG', 'Economie et Gestion');
INSERT INTO discipline (disciplineid, codecomp, namecomp, codedom, namedom) VALUES (16, 'HE', 'Institut des Hautes Etudes Européennes', 'EG', 'Economie et Gestion');
INSERT INTO discipline (disciplineid, codecomp, namecomp, codedom, namedom) VALUES (30, 'OT', 'Ecole & Observatoire des Sciences de la Terre', 'SF', 'Sciences fondamentales');
INSERT INTO discipline (disciplineid, codecomp, namecomp, codedom, namedom) VALUES (31, 'OB', 'Observatoire Astronomique', 'SF', 'Sciences fondamentales');
INSERT INTO discipline (disciplineid, codecomp, namecomp, codedom, namedom) VALUES (41, 'VI', 'Faculte des Sciences de la Vie', 'SF', 'Sciences fondamentales');
INSERT INTO discipline (disciplineid, codecomp, namecomp, codedom, namedom) VALUES (4, 'CH', 'Faculté de Chimie', 'SF', 'Sciences fondamentales');
INSERT INTO discipline (disciplineid, codecomp, namecomp, codedom, namedom) VALUES (5, 'CP', 'Ecole Européenne de Chimie, Polymères & Matériaux', 'SF', 'Sciences fondamentales');
INSERT INTO discipline (disciplineid, codecomp, namecomp, codedom, namedom) VALUES (7, 'EB', 'Ecole Supérieure de Biotechnologie de Strasbourg', 'SF', 'Sciences fondamentales');
INSERT INTO discipline (disciplineid, codecomp, namecomp, codedom, namedom) VALUES (12, 'EP', 'Ecole Nationale Supérieure de Physique', 'SF', 'Sciences fondamentales');
INSERT INTO discipline (disciplineid, codecomp, namecomp, codedom, namedom) VALUES (23, 'MI', 'UFR de Mathématique & Informatique ', 'SF', 'Sciences fondamentales');
INSERT INTO discipline (disciplineid, codecomp, namecomp, codedom, namedom) VALUES (29, 'PY', 'UFR de Physique & Ingénierie', 'SF', 'Sciences fondamentales');


INSERT INTO level (levelid, code, name) VALUES (3, '31', 'Licence 1ère année');
INSERT INTO level (levelid, code, name) VALUES (4, '32', 'Licence 2ème année');
INSERT INTO level (levelid, code, name) VALUES (5, '33', 'Licence 3ème année');
INSERT INTO level (levelid, code, name) VALUES (6, '51', 'Master 1ère année');
INSERT INTO level (levelid, code, name) VALUES (7, '52', 'Master 2ème année');
INSERT INTO level (levelid, code, name) VALUES (8, '6+', 'Doctorat');
INSERT INTO level (levelid, code, name) VALUES (1, 'O0', 'Autres');
INSERT INTO level (levelid, code, name) VALUES (2, 'C0', 'Conférence');
